name: Update a formula

on:
  workflow_dispatch:
    inputs: 
      subject:
        description: which formula to update?
        required: true
        type: choice
        options:
          - cli
          - gomod
      version:
        description: which version shall be published
        required: true
        type: string

defaults:
  env:
    UF_SUBJECT: ${{ github.event.inputs.subject }}
    UF_VERSION: ${{ github.event.inputs.version }}

jobs:
  update:
    name: "update formula: ${{ github.event.inputs.subject }} ${{ github.event.inputs.version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v4
      - name: Update Formula
        run: >
          .github/scripts/update-formula/"${UF_SUBJECT}"/gen.sh 
          "${UF_VERSION}"
          > Formula/cyclonedx-"${UF_SUBJECT}".rb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive formula
        run: TODO
  test:
    needs: [ "update" ]
    name: "Test formula"
    runs-on: macos-latest
    timeout-minutes: 10
    env:
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOMEBREW_NO_INSTALL_FROM_API: '1'
    steps:
      # https://docs.brew.sh/Adding-Software-to-Homebrew#testing-and-auditing-the-formula 
      - name: fetch formula
        run: TODO
      - name: tap
        run: |
          brew tap-new local/testing --no-git
          brew tap local/testing .
      - name: Audit & Fix Formula
        run: brew audit --fix --stric --online local/testing/cyclonedx-"${UF_SUBJECT}"
      - name: Archive formula
        run: TODO
      - name:
        run: |
          brew install --build-from-source local/testing/cyclonedx-"${UF_SUBJECT}"
          brew deps local/testing/cyclonedx-"${UF_SUBJECT}"
          brew test --verbose local/testing/cyclonedx-"${UF_SUBJECT}"
          brew uninstall local/testing/cyclonedx-"${UF_SUBJECT}"
  commit:
    permissions:
      contents: write # push commits 
      pull-requests: write # create pullrequests
    needs: [ "update", "test" ]
    name: "Commit formula"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Fetch formula
        run: TODO
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v4
      - name: Commit & Push
        run: |
          BRANCH_NAME="update-formula/${UF_SUBJECT}-${UF_VERSION}"
          git checkout -B "$BRANCH_NAME"
          git add -A Formula
          git config user.name "[BOT] Formula Updater"
          git config user.email "formula-updater@bot.local"
          git commit -s -m "Update ${UF_SUBJECT}: ${UF_VERSION}"
          git push -f --set-upstream origin "$BRANCH_NAME"
      - name: Open PullRequest
        run: gh pr create --fill-verbose --label "$UF_SUBJECT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
